# This is a generated file. Not intended for manual editing.
services:
  catalog.api:
    build:
      context: "G:\\Documentos\\Proyectos\\Varios\\EShopMicroservices\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "G:\\Documentos\\Proyectos\\Varios\\EShopMicroservices\\src\\Services\\Catalog\\\
      Catalog.API:/app:rw"
    - "G:\\Documentos\\Proyectos\\Varios\\EShopMicroservices\\src:/src:rw"
    - "G:\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
